name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: 'rj-chronicle-react-apps'
          AWS_ACCESS_KEY_ID: 'AKIAQU65GDFNJO4327HB'
          AWS_SECRET_ACCESS_KEY: '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'
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: 'dist'
